# Generated by Django 4.1.2 on 2022-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyPharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="img")),
                ("desc", models.TextField()),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
    ]
